name: CI build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:

  AWS_REGION : "us-east-1"
  TARGET_INSTANCE_ID: "test"
  ECR_REPO: "habit-api"
  AWS_ROLE_TO_ASSUME: "arn:aws:iam::227370404427:role/GitHubActionsDeployRole"
  AWS_ACCOUNT_ID: "227370404427"


# Permission can be added at job level or workflow level
permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}
      - name: Build native binary **and** container image, then push
        run: |
          ./mvnw package -Pnative \
            -Dquarkus.native.container-build=true \
            -Dquarkus.container-image.build=true \
            -Dquarkus.container-image.push=true \
            -Dquarkus.container-image.registry=${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com \
            -Dquarkus.container-image.group=${{ env.ECR_REPO }}

      - name: Build & push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_REPO }}:latest
          platforms: linux/amd64,linux/arm64   # ← makes both x86 and Arm layers
          provenance: false
  redeploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_ROLE_TO_ASSUME }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

      - name: Tell the instance to pull the new image
        run: |
          aws ssm send-command \
            --instance-ids "${{ env.TARGET_INSTANCE_ID }}" \
            --document-name "AWS-RunShellScript" \
            --comment "Redeploy Quarkus" \
            --parameters commands="docker compose -f /opt/quarkus/docker-compose.yml pull app && \
                                    docker compose -f /opt/quarkus/docker-compose.yml up -d --no-deps app"